/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nomor11;

/**
 *
 * @author resek
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        plain1 = new javax.swing.JTextField();
        chiper1 = new javax.swing.JTextField();
        encript1 = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        key1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        plain2 = new javax.swing.JTextField();
        cipher2 = new javax.swing.JTextField();
        key2 = new javax.swing.JTextField();
        encript2 = new javax.swing.JButton();
        decript2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 600));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(153, 255, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setPreferredSize(new java.awt.Dimension(500, 40));

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        jLabel1.setText("Caesar Cipher");
        jPanel4.add(jLabel1);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBackground(new java.awt.Color(255, 255, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Plain text :");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel3.setText("Cipher Text :");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        plain1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plain1ActionPerformed(evt);
            }
        });
        jPanel5.add(plain1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 140, -1));

        chiper1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiper1ActionPerformed(evt);
            }
        });
        jPanel5.add(chiper1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 140, -1));

        encript1.setText("Encript To Chiper");
        encript1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encript1ActionPerformed(evt);
            }
        });
        jPanel5.add(encript1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        hapus.setText("Clear");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel5.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        jLabel4.setText("Key :");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));
        jPanel5.add(key1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 140, -1));

        jButton1.setText("Decript to plain text");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 130, -1));

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(153, 255, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setPreferredSize(new java.awt.Dimension(500, 40));

        jLabel5.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        jLabel5.setText("Vigenere Cipher");
        jPanel6.add(jLabel5);

        jPanel3.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel7.setBackground(new java.awt.Color(255, 255, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Plain Text :");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 60, 20));

        jLabel10.setText("Cipher Text :");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel11.setText("Key :");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));
        jPanel7.add(plain2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 120, -1));
        jPanel7.add(cipher2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 120, -1));
        jPanel7.add(key2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 120, -1));

        encript2.setText("Encript To Chiper");
        encript2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encript2ActionPerformed(evt);
            }
        });
        jPanel7.add(encript2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        decript2.setText("Decript To Plain");
        decript2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decript2ActionPerformed(evt);
            }
        });
        jPanel7.add(decript2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chiper1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiper1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chiper1ActionPerformed

    private void encript1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encript1ActionPerformed
        // TODO add your handling code here:
        String plainText = plain1.getText().toLowerCase();
        int key = Integer.parseInt(key1.getText());
        String encript = CaesarEncript(plainText, key);
        chiper1.setText(encript.toUpperCase());
    }//GEN-LAST:event_encript1ActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        chiper1.setText("");
        plain1.setText("");
        key1.setText("");
    }//GEN-LAST:event_hapusActionPerformed

    private void decript2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decript2ActionPerformed
        // TODO add your handling code here:
        String enscript = cipher2.getText().toLowerCase();
         String key = key2.getText().toLowerCase();
         String plainText = vigenereDecript(enscript, key);
         plain2.setText(plainText.toUpperCase());
    }//GEN-LAST:event_decript2ActionPerformed

    private void encript2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encript2ActionPerformed
        // TODO add your handling code here:
        String plainText = plain2.getText().toLowerCase();
        String key = key2.getText().toLowerCase();
        String enscript = vigenereEncript(plainText, key);
        cipher2.setText(enscript.toUpperCase());
        
    }//GEN-LAST:event_encript2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        cipher2.setText("");
        plain2.setText("");
        key2.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void plain1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plain1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plain1ActionPerformed

    private static String CaesarEncript(String text, int shift) {
        StringBuffer sb = new StringBuffer();

        for (int i = 0; i < text.length(); i++) {
            int p = text.charAt(i) - 97;
            int e = (p + shift) % 26;
            char huruf = (char) (e + 97);
            sb.append(huruf);

        }
        return sb.toString();
    }

    private static String CaesarDecript(String text, int shift) {
        StringBuffer sb = new StringBuffer();

        for (int i = 0; i < text.length(); i++) {
            int e = text.charAt(i) - 97;
            int p = (e - shift) % 26;

            if (p < 0) {
                p += 26;
            }
            char huruf = (char) (p + 97); //untuk mengembalikan nilai aschii
            sb.append(huruf);
        }
        return sb.toString();
    }
    private static String vigenereEncript(String text, String shift){
        StringBuffer sb = new StringBuffer();
        
        int panjang = text.length();
        
        for (int i = 0; i < panjang; i++) {
            int j = i % shift.length();
            int k = (int) shift.charAt(j) - 97;
            int p = text.charAt(i) - 97;
            int e = (p + k) % 26 ;
            char huruf = (char) (e + 97);
            sb.append(huruf);
        }
        return sb.toString();
    }
    private static String vigenereDecript(String text, String shift){
        StringBuffer sb = new StringBuffer();
        
        int panjang = text.length();
        
        for (int i = 0; i < panjang; i++) {
            int j = i % shift.length();
            int k = (int) shift.charAt(j) - 97;
            int p = text.charAt(i) - 97;
            int e = (p - k) % 26 ;
            
            if (e < 0){
                e += 26;
            }
            char huruf = (char) (e + 97);
            sb.append(huruf);
            
        }
        return sb.toString();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chiper1;
    private javax.swing.JTextField cipher2;
    private javax.swing.JButton decript2;
    private javax.swing.JButton encript1;
    private javax.swing.JButton encript2;
    private javax.swing.JButton hapus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField key1;
    private javax.swing.JTextField key2;
    private javax.swing.JTextField plain1;
    private javax.swing.JTextField plain2;
    // End of variables declaration//GEN-END:variables
}
